apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadb-operator-cl-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - persistentvolumes
  - namespaces
  verbs: 
  - list
  - watch
  - get
  - create
  - delete 
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs: 
  - list
  - watch
  - get
  - create
  - delete
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - prometheuses/finalizers
  - servicemonitors
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mariadb-operator-cl-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mariadb-operator-cl-role
subjects:
  - kind: ServiceAccount
    name: mariadb-operator
    namespace: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mariadb-operator
  template:
    metadata:
      labels:
        name: mariadb-operator
    spec:
      serviceAccountName: mariadb-operator
      containers:
        - name: mariadb-operator
          image: quay.io/manojdhanorkar/mariadb-operator:v0.0.4
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 32Mi
          command:
          - mariadb-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mariadb-operator"
---
apiVersion: mariadb.persistentsys/v1alpha1
kind: MariaDB
metadata:
  name: {{ .Values.inventorydb_name }}
  namespace: {{ .Release.Namespace }}
spec:
  # Keep this parameter value unchanged.
  size: 1
  
  # Root user password
  rootpwd: root

  # New Database name
  database: default
  # Database additional user details (base64 encoded)
  username: db-user
  password: db-user

  # Image name with version
  image: {{ .Values.registry }}/inventorydb-{{ .Values.inventorydb_tech }}:{{ .Values.inventorydb_version }}

  # Database storage Path
  dataStoragePath: "/mnt/data" 

  # Database storage Size (Ex. 1Gi, 100Mi)
  dataStorageSize: "2Gi"

  # Port number exposed for Database service
  port: 30999
