apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-netem-extpayment1
  namespace: ext
spec:
  action: netem
  mode: all
  selector:
    labelSelectors:
      "tier": "payment"
  delay:
    latency: "200ms"
    correlation: "80"
    jitter: "50ms"
  direction: to
  duration: "60s"
  scheduler:
    cron: "@every 22m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-netem-extpayment2
  namespace: ext
spec:
  action: netem
  mode: all
  selector:
    labelSelectors:
      "tier": "payment"
  delay:
    latency: "1000ms"
    correlation: "80"
    jitter: "200ms"
  direction: to
  duration: "240s"
  scheduler:
    cron: "@every 500m"
