kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
      
      
      
      
      
      
      
     
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
      
      
      
      
      
      
      
      
      
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    pods: "100"
    requests.cpu: "6"
    limits.cpu: "6"
    requests.memory: 30G
    limits.memory: 30G
    persistentvolumeclaims: 10
    requests.storage: 100G
    
    
    
    
    
    
    
    
    
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-cluster-agent

















apiVersion: v1
kind: ConfigMap
metadata:
  name: action-response-services
data:
  APPDYNAMICS_LOGGER_LEVEL: "debug"
  APPDYNAMICS_LOGGER_OUTPUT_TYPE: "console"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component7 }}
spec:
  selector:
    matchLabels:
      name: action-response-services
  replicas: {{ .Values.component7_replicas }}
  template:
    metadata:
      labels:
        name: action-response-services
        app: action-response-services
    spec:
      serviceAccountName: appdynamics-cluster-agent
      containers:
        - name: {{ .Values.component7 }}
          image: astoklas/apm-game-nodejs:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 900M
            requests:
              cpu: 100m
              memory: 600M
          ports:
          - containerPort: 80
          env:
          - name: APP_CONFIG
            value: '{"type": "nodejs","agent": "no","port": 3009,"endpoints": {"http": {"actionResponseServices/updateAction": ["cache,1024", {"call": "slow,800","probability": 0.1}],"actionResponseServices/chat": ["cache,128", {"call": "slow,800","probability": 0.1}],"AuthServices/login": ["cache,128", {"call": "slow,800","probability": 0.1}],"BillingServices/purchaseGamePass": ["cache,128", {"call": "slow,800","probability": 0.1}],"/health": ["cache,128"]}},"name": "backend","nodeid": 0}'
          - name: APM_CONFIG
            value: '{"controller":"http://a.b.c.d:8090","accountName":"customer1","accountAccessKey":"secret_to_be_insert_here","applicationName":"apm_game","eventsService":"http://a.b.c.d:9080","globalAccountName":"customer1_","eum":{"appKey":"XXX-XXX-XXX","adrumExtUrlHttp":"http://cdn.appdynamics.com","adrumExtUrlHttps":"https://cdn.appdynamics.com","beaconUrlHttp":"http://a.b.c.d:7001","beaconUrlHttps":"https://a.b.c.d:7002"}}'
          - name: WITH_AGENT
            value: "0"
          - name: CUSTOM_CODE_DIR
            value: "/scripts"
          - name: LOG_DIRECTORY
            value: "logs/nodejs/backend-0/"
          - name: WITH_ANALYTICS
            value: "1"
          envFrom:
          - configMapRef:
              name: action-response-services
          command: ["/app/node.sh"]
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: action-response-services
spec:
  ports:
  - name: http
    port: 8001
    protocol: TCP
    targetPort: 80
  selector:
    app: action-response-services
---
apiVersion: v1
kind: Service
metadata:
  name: billing-services
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: action-response-services
---
apiVersion: v1
kind: Service
metadata:
  name: auth-services
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: action-response-services
    
    
    
    
    
    
    
    
    
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component8 }}
spec:
  selector:
    matchLabels:
      name: ai-services
  replicas: {{ .Values.component8_replicas }}
  template:
    metadata:
      labels:
        name: ai-services
    spec:
      serviceAccountName: appdynamics-cluster-agent
      containers:
        - name: {{ .Values.component8 }}
          image: sashaz/java-services:v5
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 900M
            requests:
              cpu: 100m
              memory: 600M
          ports:
          - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ai-services
spec:
  selector:
    name: ai-services
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  
  
  
  
  
  
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component6 }}
spec:
  selector:
    matchLabels:
      name: app-load
  replicas: {{ .Values.component6_replicas }}
  template:
    metadata:
      labels:
        name: app-load
    spec:
      containers:
        - name: {{ .Values.component6 }}
          resources:
            limits:
              cpu: 200m
              memory: 900M
            requests:
              cpu: 100m
              memory: 600M
          image: sashaz/app-load:v1
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      
      




apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component1 }}
spec:
  selector:
    matchLabels:
      name: client-api
  replicas: {{ .Values.component1_replicas }}
  template:
    metadata:
      labels:
        name: client-api
        tier-name: client-api-tier
        application-name: OS-App
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
      serviceAccountName: appdynamics-cluster-agent
      containers:
        - name: {{ .Values.component1 }}
          image: sashaz/java-services:v5
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 900M
            requests:
              cpu: 100m
              memory: 600M
          ports:
          - containerPort: 8080
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component5 }}
spec:
  selector:
    matchLabels:
      name: web-api
  replicas: {{ .Values.component5_replicas }}
  template:
    metadata:
      labels:
        name: web-api
        tier-name: web-api-tier
        application-name: OS-App
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
      serviceAccountName: appdynamics-cluster-agent
      containers:
        - name: {{ .Values.component5 }}
          image: sashaz/java-services:v5
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 900M
            requests:
              cpu: 100m
              memory: 600M
          ports:
          - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: client-api
spec:
  selector:
    name: client-api
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
spec:
  selector:
    name: web-api
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  
  
  
  
  
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.component11 }}
  labels:
    app: devminion
spec:
  replicas: {{ .Values.component11_replicas }}
  selector:
    matchLabels:
      app: devminion
  template:
    metadata:
      labels:
        app: devminion
    spec:
      containers:
        - name: {{ .Values.component11 }}-cpu
          image: 'beekman9527/cpumemload:latest'
          env:
            - name: RUN_TYPE
              value: cpu
            - name: CPU_PERCENT
              value: '90'
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 240m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - name: {{ .Values.component11 }}-mem
          image: 'beekman9527/cpumemload:latest'
          env:
            - name: RUN_TYPE
              value: memory
            - name: MEMORY_NUM
              value: '910'
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      
 
 
 
 
 
 
 
 
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.component10 }}
  labels:
    app: devminion
spec:
  replicas: {{ .Values.component10_replicas }}
  selector:
    matchLabels:
      app: devminion
  template:
    metadata:
      labels:
        app: devminion
    spec:
      nodeSelector:
        capability: gpu
      containers:
        - name: {{ .Values.component10 }}
          image: 'beekman9527/cpumemload:latest'
          env:
            - name: RUN_TYPE
              value: cpu
            - name: CPU_PERCENT
              value: '90'
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 240m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      
      
      
      






apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component9 }}
spec:
  selector:
    matchLabels:
      name: player-action-services
  replicas: {{ .Values.component9_replicas }}
  template:
    metadata:
      labels:
        name: player-action-services
        tier-name: player-action-services-tier
        application-name: OS-App
    spec:
      serviceAccountName: appdynamics-cluster-agent
      containers:
        - name: {{ .Values.component9 }}
          image: sashaz/java-services:v5
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 600M
            limits:
              cpu: 200m
              memory: 900M
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: player-action-services
spec:
  selector:
    name: player-action-services
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  
 
  
  
  
  
  
  
  






apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component2 }}
spec:
  selector:
    matchLabels:
      name: world-change-services
  replicas: {{ .Values.component2_replicas }}
  template:
    metadata:
      labels:
        name: world-change-services
        tier-name: world-change-services-tier
        application-name: OS-App
    spec:
      serviceAccountName: appdynamics-cluster-agent
      containers:
        - name: {{ .Values.component2 }}
          image: sashaz/java-services:v5
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 900M
            requests:
              cpu: 100m
              memory: 600M
          ports:
          - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: world-change-services
spec:
  selector:
    name: world-change-services
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component4 }}
spec:
  selector:
    matchLabels:
      name: world-generator
  replicas: {{ .Values.component4_replicas }}
  template:
    metadata:
      labels:
        name: world-generator
        tier-name: world-generator-tier
        application-name: OS-App
    spec:
      serviceAccountName: appdynamics-cluster-agent
      containers:
        - name: {{ .Values.component4 }}
          image: sashaz/java-services:v5
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "400M"
              cpu: "250m"
            limits:
              memory: "1000M"
              cpu: "500m"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: world-generator
spec:
  selector:
    name: world-generator
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  
  
  
  
  
  
  
  
  
  
  
  


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component3 }}
spec:
  selector:
    matchLabels:
      name: world-portal
  replicas: {{ .Values.component3_replicas }}
  template:
    metadata:
      labels:
        name: world-portal
        tier-name: world-portal-tier
        application-name: OS-App
    spec:
      serviceAccountName: appdynamics-cluster-agent
      containers:
        - name: {{ .Values.component3 }}
          image: sashaz/java-services:v5
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 900M
            requests:
              cpu: 100m
              memory: 600M
          ports:
          - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: world-portal
spec:
  selector:
    name: world-portal
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-front-end
spec:
  selector:
    name: world-portal
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
