apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-fulfilment
  namespace: {{ .Release.Namespace }}
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      "app": {{ .Values.app_name }}
      "tier": "fulfilment"
  scheduler:
    cron: "@every 275m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill-adminfile
  namespace: {{ .Release.Namespace }}
spec:
  action: container-kill
  mode: one
  containerName: "fileserver"
  selector:
    labelSelectors:
      "app": {{ .Values.app_name }}
      "tier": "adminfile"
  scheduler:
    cron: "@every 22m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-netem-inventorydb
  namespace: {{ .Release.Namespace }}
spec:
  action: netem
  mode: all
  selector:
    labelSelectors:
      "app": "MariaDB"
  delay:
    latency: "200ms"
    correlation: "80"
    jitter: "900ms"
  direction: to
  duration: "75s"
  scheduler:
    cron: "@every 550m"
