apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-fulfilment
  namespace: order
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      "app": "demo-order"
      "tier": "fulfilment"
  scheduler:
    cron: "@every 275m"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-netem-inventorydb
  namespace: order
spec:
  action: netem
  mode: all
  selector:
    labelSelectors:
      "app": "MariaDB"
  delay:
    latency: "200ms"
    correlation: "80"
    jitter: "900ms"
  direction: to
  duration: "75s"
  scheduler:
    cron: "@every 550m"
